import type { InstructionAccountData } from '@entities/idl';
import { Autocomplete } from '@shared/ui/autocomplete';
import { Badge } from '@shared/ui/badge';
import { Label } from '@shared/ui/label';
import { Tooltip, TooltipContent, TooltipTrigger } from '@shared/ui/tooltip';
import Image from 'next/image';
import { forwardRef, useState } from 'react';
import { Info } from 'react-feather';

import StarsIcon from '@/app/img/icons/stars.svg';

import type { AutocompleteItem } from '../model/account-autocomplete/types';

export interface AccountInputProps extends React.ComponentProps<'input'> {
    account: InstructionAccountData;
    error: { message?: string | undefined } | undefined;
    autocompleteItems?: AutocompleteItem[];
    seeds: { name: string }[];
}

export const AccountInput = forwardRef<
    HTMLInputElement,
    Omit<AccountInputProps, 'onChange'> & {
        // This type serves as an intermediary between the autocomplete component and the react-hook-form component
        onChange: (value: { target: { value: string }; currentTarget: { value: string } }) => void;
    }
>(({ account, error, onChange, autocompleteItems = [], seeds, ...props }, ref) => {
    const [inputId, setInputId] = useState('');

    return (
        <div className="e-space-y-2">
            <div className="e-flex e-items-center e-gap-2">
                <Label className="e-text-sm e-font-normal e-text-neutral-200" htmlFor={inputId}>
                    {account.name}
                </Label>
                <div className="e-flex e-gap-1">
                    {account.writable && (
                        <Badge variant="warning" size="xs">
                            Mutable
                        </Badge>
                    )}
                    {account.signer && (
                        <Badge variant="warning" size="xs">
                            Signer
                        </Badge>
                    )}
                    {account.pda && (
                        <Tooltip>
                            <TooltipTrigger asChild>
                                <div className="e-inline-flex e-cursor-default e-items-center">
                                    <Badge variant="info" size="xs">
                                        PDA
                                        <Info className="e-h-4 e-w-4" />
                                    </Badge>
                                </div>
                            </TooltipTrigger>
                            <TooltipContent>
                                <div className="e-min-w-40 e-max-w-full">
                                    Can be generated from the next arguments:
                                    <div className="e-text-teal-400">{seeds.map(seed => seed.name).join(', ')}</div>
                                </div>
                            </TooltipContent>
                        </Tooltip>
                    )}
                    {account.optional && (
                        <Badge variant="secondary" size="xs">
                            Optional
                        </Badge>
                    )}
                </div>
            </div>
            <Autocomplete
                items={autocompleteItems}
                value={String(props.value)}
                renderItemContent={option => <AutocompleteItemContent option={option} seeds={seeds} />}
                onChange={value => {
                    onChange({
                        currentTarget: { value },
                        target: { value },
                    });
                }}
                inputProps={{
                    'aria-invalid': Boolean(error),
                    ref,
                    variant: 'dark',
                }}
                onInputIdReady={setInputId}
            />
            {account.docs.length > 0 && <p className="e-text-xs e-text-neutral-400">{account.docs.join(' ')}</p>}
            {error && <p className="e-mt-1 e-text-xs e-text-destructive">{error.message}</p>}
        </div>
    );
});

AccountInput.displayName = 'AccountInput';

function AutocompleteItemContent({ option, seeds }: { option: AutocompleteItem; seeds: { name: string }[] }) {
    return (
        <div className="e-flex e-w-full e-items-start e-justify-between e-px-4 e-py-1.5 e-text-xs">
            <span className="e-hidden md:e-inline">
                {option.label}
                {option.generated && (
                    <Image src={StarsIcon} alt="Account autogenerated PDA" height={16} width={16} className="e-ml-2" />
                )}
            </span>
            <span className="e-font-mono e-text-xs e-text-white md:e-ml-2 md:e-text-heavy-metal-400">
                {option.value || 'Enter all required arguments to generate PDA'}
                {option.generated && (
                    <div className="e-flex e-max-w-96 e-justify-end">
                        Arguments: {seeds.map(seed => seed.name).join(', ')}
                    </div>
                )}
            </span>
        </div>
    );
}
