import { formatDisplayIdl } from './format-display-idl';
import { formatSerdeIdl } from './format-serde-idl';
import type { IdlFormatter } from './formatted-idl';

/// Problem: formatSerdeIdl(aka formatIdl ./formatters/format-serde-idl.ts ) is used to produce Idl to create a Program instance, but needed to display Idl also
// Upon displaying Idl, we discovered new spec-type that is likely generated by Shank.
// Having this, we can not just introduce new switch-case. That potentially leads to degradation
//
// Solution: implement wrapper that will use formatIdl's signature as a provider
// That allows to keep current functionality to create Program instances
// That also allows to have a separate output according the spec-type of Idl
export function getFormattedIdl(formatter: IdlFormatter, idl: any, programAddress?: string): ReturnType<IdlFormatter> {
    return formatter(idl, programAddress);
}

export { formatDisplayIdl, formatSerdeIdl };
